name: Production
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # Runs only on semantic versioning tags (vMAJOR.MINOR.PATCH)

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    deploy:
        name: "Build docker and publish to ECR"
        runs-on: ubuntu-latest

        steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: assets/polkadot-auth-api
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }} .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name }}