name: Stage

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: "assetportal/polkadot-auth-api"

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag ${{ env.IMAGE_REPO }}:${{ github.sha }} \
            --push .
